### ISSUE TITLE
Add contributors section

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/anem-per-feina#102]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Will be great if we thank all contributors for their efforts with an explicit section in this repo :)

**Describe alternatives you've considered**

Create a contributors file, or define a section in the README.

Some ideas: https://github.com/all-contributors/all-contributors

Thoughts?

**Comment by victormartingarcia** [comment]
cool idea! 

+1 for creating a new section on README file, so we all be in frontpage :)
