### ISSUE TITLE
Provide multilanguage support

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/anem-per-feina#11]
Internationalization (i18n) should be provided.

At least we should support locales (and formats) for:
- Catalan
- Spanish
- English

**Comment by francescarpi** [comment]
Use this ticket only for configure multilingual. Add the LANGUAGES attribute in settings and create the locale folders.

**Comment by XaviTorello** [comment]
We deployed Weblate for out translations at https://weblate.geekscat.org/projects/anem-per-feina/, if someone want to contribute register and propose changes :)
