### ISSUE TITLE
Create a make command to execute makemigrations

### ISSUE THREAD

**Issue by jbagot** [GeeksCAT/anem-per-feina#122]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I want a new make command to execute the makemigrations. Now it's difficult to execute makemigrations because you have to go inside of the container and execute the `python manage.py makemigrations`. The idea is to have a make command that will execute it inside the container and the migrations files will appear in your local. This will be automatically because we already have the volumes.
The problem is that we cannot execute the `docker-compose run app python manage.py makemigrations` because we need an entrypoint that enables python in the dockerfile.

**Comment by fullonic** [comment]
Fixed by #131
