### ISSUE TITLE
Remove Github login button

### ISSUE THREAD

**Issue by jbagot** [GeeksCAT/anem-per-feina#165]
**Checklist**

- [x] I have verified that that issue exists against the `master` branch.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [Slack](https://geekscat.slack.com) instead.)
- [x] I have reduced the issue to the simplest possible case.

**Describe the bug**
GIthub social auth is not working, we should check and fix the issue.

**Comment by jbagot** [comment]
For now I'll remove the button due a time restriction, I'll comment the button and in the future we should check the real issue and fix it keeping the github social auth

**Comment by XaviTorello** [comment]
Fixed in #176
