### ISSUE TITLE
Use a proper DB

### ISSUE THREAD

**Issue by jbagot** [GeeksCAT/anem-per-feina#17]
Now the app is using sqlite. We have to change it for a proper DB, like PostgreSQL for example.
I recommend to use a docker container with the DB.
This task can be related with the Dockerize app task

**Comment by mcastellin** [comment]
@jbagot we can introduce PostgreSQL as soon as we introduce the docker compose. This way it's going to be easier for anyone to spin up the application stack.

I'm going to take a look at the application to see if there's anything to do to replace sqllite, in that case we can create an issue with the development team to arrange for a configuration file or environment variable we can customize in the containerization

**Comment by mcastellin** [comment]
Hello guys, I wanted to start working on this issue with an additional couple of points:
- Create the docker compose file
- Use docker-compose secrets to set DB password in DB init and application
- Drop user privileges in containerized application

@XaviTorello @jbagot let me know if you think of anything else that should be included with this issue. I will assign this issue to myself and start working on it

**Comment by mcastellin** [comment]
@jbagot do you think this one can be closed after we created the docker-compose or you still think we have work to do about it?

**Comment by XaviTorello** [comment]
I think this has been solved, @jbagot?

**Comment by jbagot** [comment]
Yes, we can close this one. Thank you :+1:
