### ISSUE TITLE
Basic improvements

### ISSUE THREAD

**Issue by francescarpi** [GeeksCAT/anem-per-feina#25]
The project needs basic improvements before start the other tickets.

**Not to use  final urls**

![image](https://user-images.githubusercontent.com/287872/94897864-c90ff500-0490-11eb-8ec9-f3f50ee0ee41.png)

It's better to use _reverse_lazy_

**Replace some  "__unicode__"  by "__str__"

![image](https://user-images.githubusercontent.com/287872/94897999-12f8db00-0491-11eb-87cb-11056b021381.png)

**Check if inheritances are being used correctly**

For example in this case, to check if it's better to use "form_valid".

![image](https://user-images.githubusercontent.com/287872/94898179-68cd8300-0491-11eb-8d57-f289f526d467.png)

**Check settings**

Check the default settings. For example, DEBUG must be False by default. Use _os.environ.get_

![image](https://user-images.githubusercontent.com/287872/94898502-f6a96e00-0491-11eb-9197-a2fee3cd0012.png)

**Comment by fullonic** [comment]
Would be nice remove as well all the `*` imports 
```python
from module_name import *

**Comment by francescarpi** [comment]
Yes, I got it in this branch!
https://github.com/GeeksCAT/anem-per-feina/tree/_25_basic_improvements

xDD

**Comment by fullonic** [comment]
ahh great, I will update my upstream branch to have get your changes :)
