### ISSUE TITLE
Create k8s manifests backend

### ISSUE THREAD

**Issue by jbagot** [GeeksCAT/anem-per-feina#29]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Create the manifests to deploy the app to the kubernetes cluster. If we decide to use helm, create the helm chart instead.

**Describe alternatives you've considered**
Depending if use helm or not

**Additional context**
We need to deploy the app to a kubernetes cluster. To deploy to k8s we need manifests or we need to use helm. And these files will be used in the CD to deploy the app automatically.

**Comment by XaviTorello** [comment]
I'm going to split in two issues
- #29 k8s manifests for backend
- #97 Helm Charts for backend
