### ISSUE TITLE
Dockerize backend

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/anem-per-feina#3]
The env should be standardized.

A base Docker image should be created

Ideal to be reused for local testing, CI and deployment

Some ideas to go further
- prepare a docker composition
- turn it k8s-deployable
- provide Helm Chart

**Comment by mcastellin** [comment]
@XaviTorello if it's available for the Hacktoberfest can you please assign it to me? I would love to help

**Comment by XaviTorello** [comment]
Great! Many thanks @mcastellin! 🍻 

I'll write you via Gitter to discuss it. Just a summary: our initial idea is to define some teams (isolated by functional branch, I mean, dev / devops / UX / isec / ....) and start working on it following a global roadmap. The kickoff session will be performed next thursday (November 1th) via Zoom/Hangouts will all interested people.

Here you will find more information about the event that we propose: https://hacktoberfest.geekscat.org/ (sorry it's just in catalan)
