### ISSUE TITLE
Add django-constance

### ISSUE THREAD

**Issue by francescarpi** [GeeksCAT/anem-per-feina#31]
**Is your feature request related to a problem? Please describe.**
We need a system for manage constants in our project. We could use settings.py, but it not allow to change the values in execution time. We should may to change this values from the admin site.

**Describe the solution you'd like**
The possible solution is to use django-constance that allow us to define some constants in the settings.py and change values in execution time. Also it allows to use redis for cache.

https://github.com/jazzband/django-constance

**Describe alternatives you've considered**
No alternatives at the moment

**Additional context**
No additional context at the moment

**Comment by francescarpi** [comment]
Nice Xavier. 

You can start whenever you want. Don't forget change to "in progress" when you start it.

**Comment by fullonic** [comment]
@francescarpi  Maybe we can close this issue. It as solved with #65
