### ISSUE TITLE
Add functional tests

### ISSUE THREAD

**Issue by francescarpi** [GeeksCAT/anem-per-feina#35]
**Is your feature request related to a problem? Please describe.**
At the moment does not exist any test.

**Describe the solution you'd like**
The first step could be add functional tests on the current flow. Maybe is not necessary on django views, only test the apis. Because the views will desapear.

**Describe alternatives you've considered**
Nope

**Additional context**

**Comment by francescarpi** [comment]
At the moment we can test de API.

* Login
* Get jobs

**Comment by ilyassjaatit** [comment]
I take this issue.
