### ISSUE TITLE
Configure redis

### ISSUE THREAD

**Issue by francescarpi** [GeeksCAT/anem-per-feina#38]
**Is your feature request related to a problem? Please describe.**
django constance can use redis to cache the constant's values. At the moment we have not configure it in the project.

**Describe the solution you'd like**
Update the settings adding redis configuration as a cache.
We will need to add this package:
https://github.com/jazzband/django-redis

**Describe alternatives you've considered**
After that, create a new issue for arch & CI. They need to dockerize it .

**Additional context**
Nope

**Comment by wolframtheta** [comment]
For completing task of constance, i think i could do this issue!

**Comment by francescarpi** [comment]
Redis already implemented in related issues. Can be closed.
