### ISSUE TITLE
Add python-black and configure linter

### ISSUE THREAD

**Issue by francescarpi** [GeeksCAT/anem-per-feina#40]
**Is your feature request related to a problem? Please describe.**
We have not any linter and it's important to follow PEP8. For this reason, it's important add any linter.

**Describe the solution you'd like**
Add python-black in requirements, documentate and explay to team how to use it.
Also configure any linter (flake8 or pylint)

**Describe alternatives you've considered**
Nope

**Additional context**
Nope

**Comment by fullonic** [comment]
Should we also add type annotations in our code? or at least to the new code we add? If so, we could add mypy as well.

**Comment by francescarpi** [comment]
Yes, I would like it. Although it's not necessary install mypy, right? Python3 already have type hints.

https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html

**Comment by fullonic** [comment]
Mypy as type hints linter, to sure that the types are what should be.

**Comment by francescarpi** [comment]
Ah! I didn't know about that. Ok! Nice!

**Comment by ytturi** [comment]
I think mypy is a bit more complex to add as it will check the whole structure and right now we are not using types.
The sooner the better but we have to change everything...

What we can do is check for "recently" changed files only. This way the test will pass easier.
Once we update the whole codebase we can remove this if.
We may need a small script to do so.
I think it's better if we consider implementing it in another issue.

**Comment by fullonic** [comment]
Yep, I agreed as well.
