### ISSUE TITLE
Changes on README

### ISSUE THREAD

**Issue by victormartingarcia** [GeeksCAT/anem-per-feina#58]
We need changes on README file to better communicate:

**What is this project**: A django application for managing job postings. Forked from [django-job-portal](https://github.com/manjurulhoque/django-job-portal) repository
**Screenshots**
**How to run it**: How to run it on dev (local) environment. How to run it on production environment.
**How to contribute**: Link to CONTRIBUTE file. Explaining this is a collaborative effort promoted by GeeksCat association for Hacktoberfest 2020 edition

**Comment by danifornells** [comment]
That would be great !!
I was thinking on contributing, however, by not being a pythonist found no way to run the app locally. I would like to contribute somehow, maybe enabling CI e2e tests via actions.

Anyway, I'm feeling blocked until:
- README contains a getting started info
- or #63 reaches master so I can run the app via Docker & the info provided
- or a stable environment is available remotely

Best 😉

**Comment by victormartingarcia** [comment]
Good to see you here @danifornells !!! :)

I think we do already have the docker compose in place, let me work on the README with some simple instructions for spinning up a dev env

**Comment by danifornells** [comment]
Thank you @victormartingarcia, much appreciated. It's now up & running on my local environment. Will try to collaborate somehow 😘
