### ISSUE TITLE
Identify if a job offer permits remote working

### ISSUE THREAD

**Issue by ctrl-alt-d** [GeeksCAT/anem-per-feina#66]
# Backgrounds

At this stage, there is not a checkbox to indicate if a job vacancies is a remote job.

# Issue

Nowadays, many people need to know if a job is remote. People can apply to a job in another city or country if it's a remote job or just work remotely because it offers a more flexible lifestyle.

![95682136-f58be580-0be3-11eb-8dd3-39da63273941](https://user-images.githubusercontent.com/3105983/95900326-01b5a580-0d92-11eb-81b7-4746be61290b.png)

# Potential approaches

## Solution 1

Do nothing. This info can be included on Job Description field.

_be free to vote with :-1:_

## Solution 2 

Add "Is remote" on `Jobs` as a new field:

_be free to vote with :+1:_

```python
class Job(models.Model):
    # ...
    is_remoting = models.BooleanField("Is remoting", default=False, )
```

## Other alternative solutions.

_please, be free to post your own as a new comment._

# More screenshots

![image](https://user-images.githubusercontent.com/3105983/95901284-64f40780-0d93-11eb-9e9c-143cdfb96be5.png)

**Comment by XaviTorello** [comment]
Great, many thanks @ctrl-alt-d 🍻 

I think that this will improve job offer details :)

Just as an idea, maybe is a good approach if we try to identify the list of possible values instead of a boolean flag: 
- no remote
- partially remote
- full remote
- ...

Thoughts?

**Comment by xdiume** [comment]
@ctrl-alt-d @XaviTorello perhaps a better solution could be a percentage where 0% is no remote and 100% is fully remote, allowing values with 10 units steps. Also with a comment if details are needed.
