### ISSUE TITLE
Job Salary: should be a range?

### ISSUE THREAD

**Issue by ctrl-alt-d** [GeeksCAT/anem-per-feina#68]
# Background

The job vacancies has a "Salary" field:

```python
class Job(models.Model):
    # ...
    salary = models.IntegerField(default=0, blank=True)
```

Screenshot:

![Job screenshot with salary field](https://user-images.githubusercontent.com/3105983/95903419-6d017680-0d96-11eb-96ab-e634a462c8db.png)

# Issue

Usually, companies post vacancies without salary or with a salary range:

![Vacancies screenshot with salary range](https://user-images.githubusercontent.com/3105983/95903780-e8632800-0d96-11eb-93d3-0ebe37f4ce11.png)

And applicants search offers for a minimum annual salary:

![Sample searching for a minimum annual salary](https://user-images.githubusercontent.com/3105983/95904090-4f80dc80-0d97-11eb-8e1d-a716f5567741.png)

# Potential approaches

## Solution 1

Do nothing. This info can be included on Job Description field.

_be free to vote with :-1:_

## Solution 2 

Change salary by a salary range (annual_salary_max and annual_salary_min or external package like [inclusive-django-range-fields](https://github.com/Hipo/inclusive-django-range-fields)). Also, maybe allow null on values.

_be free to vote with :+1:_

## Other alternative solutions.

_please, be free to post your own as a new comment._

**Comment by francescarpi** [comment]
And for prevent confusions, add a `help_text` in the salary model's attribute indicating if it's monthly or yearly.  It's most common to use "yearly", but in the current views, appear "monthly". Rare.

![image](https://user-images.githubusercontent.com/287872/96360506-2907cc00-111e-11eb-9a0d-2a3c6896e756.png)
