### ISSUE TITLE
Notifications plugins

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/anem-per-feina#8]
Notifications should be standardized defining plugins.

It will contribute to #2 make it more hackable, and will simplify the possibility to support new channels without added complexity

Think about the possibility to
- [ ] provide SMTP notification plugin
- [ ] provide Telegram notification plugin
- [ ] provide Twitter notification plugin
- [ ] provide WebHooks

**Comment by francescarpi** [comment]
I take this issue.

https://hackmd.io/KKWiYEVJRNWAYG4Aoj7nTA?view

**Comment by francescarpi** [comment]
Related with #38
