### ISSUE TITLE
"code-check -> Run checks" step is not executed properly on GH actions

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/anem-per-feina#82]
**Checklist**

- [X] I have verified that that issue exists against the `master` branch.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [Slack](https://geekscat.slack.com) instead.)
- [X] I have reduced the issue to the simplest possible case.

**Describe the bug**

`Run checks` step of `code-check` raises because seems to not be able to identify `origin/master`.
```
Run python checks.py --since origin/master --typing
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Finding files with the following command:  git diff --name-only origin/master HEAD | grep '.py$' | grep -vE './*/migrations'
No files found to check
Error: Process completed with exit code 255.
```
Maybe is easier to fix than request directly `master` instead of passing the remote, but some investigation should be performed.

**To Reproduce**

Review any existing execution, ie https://github.com/GeeksCAT/anem-per-feina/runs/1252568197?check_suite_focus=true

**Expected behavior**

This step should be executed as expected

**Screenshots**

https://github.com/GeeksCAT/anem-per-feina/runs/1252568197?check_suite_focus=true
![image](https://user-images.githubusercontent.com/8709244/95971396-78de4e80-0e11-11eb-93c3-3794869614d6.png)

**Comment by XaviTorello** [comment]
cc: @ytturi

**Comment by ytturi** [comment]
Yeah it worked locally because I have the remote, however in github actions it doesn't.
We should change the action to run with master instead.

**Comment by ytturi** [comment]
Since we are muting the output, we could just replace the script by adding mypy to all the repo, in a different step for now (just as the checks script)

**Comment by ytturi** [comment]
I've done some tests in #87 , seems like it doesn't even recognize the commit hash... not sure why so I would just change the strategy and go for what my last message says: lets just run mypy for the whole repo everytime.
